FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY embeddings_server_requirements.txt .
RUN pip install -r embeddings_server_requirements.txt

COPY embeddings_server.py .

CMD ["python", "embeddings_server.py"]